In [1]:
!pip install numpy

Collecting numpy
  Using cached numpy-2.4.4-cp313-cp313-win_amd64.whl.metadata (6.6 kB)
Using cached numpy-2.4.4-cp313-cp313-win_amd64.whl (12.3 MB)
Installing collected packages: numpy
Successfully installed numpy-2.4.4

[notice] A new release of pip is available: 26.0.1 -> 26.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [8]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
music = pd.read_csv("SpotifySongs.csv")

In [3]:
music.head()

,SongName,ArtistName,Popularity,Danceability,Energy,Key,Loudness,Mode,Speechiness,Acousticness,Instrumentalness,Liveness,Valence,Tempo,Duration_ms
0,Saiyaan Ji,Yo Yo Honey Singh,62,0.896,0.678,0,-2.546,0,0.0815,0.0137,0.000041,0.1100,0.604,130.024,205450
1,Falling,Trevor Daniel,84,0.785,0.431,10,-8.756,0,0.0364,0.1230,0.000000,0.0887,0.236,127.085,159382
2,Shayad,Pritam,72,0.483,0.468,8,-7.642,1,0.0341,0.7850,0.000000,0.1520,0.319,135.864,247941
3,"Malang (Title Track) [From ""Malang - Unleash T...",Ved Sharma,68,0.384,0.728,7,-6.503,0,0.0623,0.3290,0.000018,0.3290,0.311,156.396,287374
4,Genda Phool (feat. Payal Dev),Badshah,67,0.955,0.538,1,-8.394,1,0.0734,0.1320,0.001460,0.0704,0.837,116.977,170769

In [4]:
music = music[['SongName','ArtistName','Popularity', 'Danceability', 'Loudness','Tempo']]

In [5]:
music.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3731 entries, 0 to 3730
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   SongName      3731 non-null   object
 1   ArtistName    3731 non-null   object
 2   Popularity    3731 non-null   int64
 3   Danceability  3731 non-null   float64
 4   Loudness      3731 non-null   float64
 5   Tempo         3731 non-null   float64
dtypes: float64(3), int64(1), object(2)
memory usage: 175.0+ KB

In [6]:
music.shape

(3731, 6)

In [7]:
music.isna().sum()

SongName        0
ArtistName      0
Popularity      0
Danceability    0
Loudness        0
Tempo           0
dtype: int64

In [10]:
music.sample(5)

,SongName,ArtistName,Popularity,Danceability,Loudness,Tempo
2251,Mad at Disney,salem ilese,55,0.728,-3.992,112.071
3097,Arcade,Duncan Laurence,73,0.675,-6.934,99.865
245,Adventure of a Lifetime,Coldplay,78,0.730,-4.100,117.965
3624,Bloodstream,Stateless,80,0.403,-13.964,122.728
3085,Hymn for the Weekend - Seeb Remix,Coldplay,84,0.444,-4.078,82.695

In [18]:
from sklearn.preprocessing import StandardScaler
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.model_selection import train_test_split

In [35]:
features = ['Popularity', 'Danceability', 'Loudness','Tempo']

In [37]:
X = music[features]

In [38]:
scalar =  StandardScaler()

scalar.fit(X)

X_scaled = scalar.transform(X)

In [40]:
scalar.mean_

array([ 65.06647012,   0.60545773,  -7.61021951, 119.27320102])

In [47]:
similarity = cosine_similarity(X_scaled)

In [48]:
similarity.shape

(3731, 3731)

In [71]:
def recommend(song):
    music_index = music[music['SongName'] == song].index[0]
    distances = similarity[music_index]
    music_list = sorted(list(enumerate(distances)), reverse = True, key = lambda x:x[1])[1:6]
    for i in music_list:
        print(music.iloc[i[0]].SongName)

In [74]:
recommend('Kiss Me Thru The Phone')

Gone Are The Days (feat. James Gillespie)
Sing It With Me
New Thang
anxiety (with FRND)
Beautiful Now

In [75]:
import pickle

In [78]:
pickle.dump(music.to_dict(), open('music_dict.pkl','wb'))

In [79]:
pickle.dump(similarity, open('similar.pkl','wb'))